n1 = input('Digite aqui: ')
print('Todas as palavras vão começar com maiusculo\n{}'.format(n1.title()))
print('-' * 30)
print('Só a primeira palavra começará com maiusculo\n{}'.format(n1.capitalize()))
print('-' * 30)
print('Tudo minusculo\n{}'.format(n1.lower()))
print('-' * 30)
print('Tudo maiusculo\n{}'.format(n1.upper()))
print('-' * 30)
print('Vai trocar silva por park\n{}'.format(n1.replace('silva', 'Park')))
print('-' * 30)
print('Vai falar se tem gama na frase ou não\n {}'.format('gama' in n1))
print('-' * 30)
print('Onde começa gama\n{}'.format(n1.find('gama')))
print('-' * 30)
print('Quantos a tem\n{}'.format(n1.count('a', 0, 13)))
print('-' * 30)
frase = input('Digite Algo: ')
print('Exclui os espaços do começo e do final\n{}'.format(frase.strip()))
print('Exclui os espaços do final, como se começasse pela direita\n{}'.format(frase.rstrip()))
print('Exclui os espaços do lado esquerdo de left\n{}'.format(frase.lstrip()))
